name: Hello
#one workflow have n of jobs
#trigger workflow
on: push
#using jobs we give steps
#one job have n of steps
jobs:
  hello:
    #which VM we need to run jobs, now run on ubutu latest
    runs-on: ubuntu-latest
    #use hypen to give list
    steps:
      - name: Print Hello World
        #run to run command
        run: echo "Hello Wold"

#after all the jobs finish it(VM) will automatically close,